### ISSUE TITLE
Add supported API version to README

### ISSUE THREAD

**Issue by blankenshipz** [softprops/shiplift#53]
I don't think that `v1.26` of the remote API is currently supported, I think the README should be updated with information related to the minimum and max supported versions.

**Comment by blankenshipz** [comment]
I added a `Dockerfile` and `docker-compose.yml` locally to test against a specific version of the API:

```dockerfile
# Dockerfile
FROM liuchong/rustup:stable

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY . /usr/src/app

CMD ["cargo", "run"]
```

```yaml
# docker-compose.yml
version: '2'

services:
  app: &default
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - dockerapi
    volumes:
      - .:/usr/src/app
      - registry:/root/.cargo/registry # Allows for caching dependencies 

  dockerapi:
    image: docker:1.12.6-dind
    privileged: true

volumes:
  registry:
    driver: local
```

This allows for running an application that uses`shiplift` against a known version of the docker remote api using the `dind` image.
